services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres # Demo credentials for local dev purposes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polling_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
